[package]
name = "calibre-lir"
version = "0.1.0"
edition = "2024"

[dependencies]
calibre-mir = {path = "../mir"}
calibre-mir-ty = {path = "../mir-ty"}
calibre-parser = {path = "../parser"}
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
