[package]
name = "cal-lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
async-lsp = { version = "0.2.2", features = ["tokio"] }
calibre-parser = {path = "../crates/parser"}
cal-fmt = {path = "../fmt"}
tokio = { version = "1.47.1", features = ["full"] }
tower = { version = "0.5.2", features = ["full", "tokio"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
