[package]
name = "calibre-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
calibre-lir = {path = "../lir"}
calibre-mir-ty = {path = "../mir-ty"}
calibre-parser = {path = "../parser"}
rand = "0.9.1"
rustyline = "16.0.0"
thiserror = "2.0.12"
rustc-hash = "2.1.1"
